apiVersion: v1 
kind: Service 
metadata: 
  name: loan-demo-service
spec:
  selector:
    app: loan-demo-app
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 2022 
  type: LoadBalancer