apiVersion: v1
kind: Service
metadata:
  name: mysql-service  
  labels:
    app: mysql
spec:
  ports:
  - nodePort: 30036
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort